### ISSUE TITLE
Is your encoder fixed or progrresive growing?

### ISSUE THREAD

**Issue by 1900zyh** [jerryli27/TwinGAN#13]
Thanks for your work ,it's really interesting. 
btw, I wonder is your encoder fixed and linear training, or in a progrresive growing? 
thx a lot!

**Comment by jerryli27** [comment]
The encoder uses a progressively growing structure, so it first outputs 4x4, then 8x8, etc., all the way to 256x256. Please check [Progressive GAN](https://arxiv.org/abs/1710.10196) for more detail!

**Comment by 1900zyh** [comment]
@jerryli27 Thank you for your quick response very much. 
But did you mean decoder? In PGGAN, it has just generator and discriminator with mirrored structure. 
I wonder in your framework (I'm sorry that I didn't find out the framework illustration in your paper),
does the encoder take image of original size as input then map it into latent vector in a fixed structure, 
Or does the encoder take  4x4, then 8x8, etc., downsampled image as input and map it into latent vector?

I mean **encoder**, **not decoder or discriminator.**

**Comment by jerryli27** [comment]
Oh sorry I misunderstood. The encoder does grow along with decoder and discriminator. The encoder basically shares the same structure as the discriminator. I didn't add an illustration in the current version of the paper, but you can check either the appendix or the source code for the network structure.
