### ISSUE TITLE
Why the channel changed after first downsample

### ISSUE THREAD

**Issue by nyannnnnnn** [jerryli27/TwinGAN#25]
From the supplementary of your technical report
![1091554204654_ pic](https://user-images.githubusercontent.com/14358291/55399499-d9829f00-557d-11e9-8c80-6008607c8bb6.jpg)
Why the channel changed?
Thanks!

**Comment by jerryli27** [comment]
Hi,
Thanks for pointing it out. It was a typo. The conv number of channels should've been 32 instead of 16 in the 256 layers. Sorry about that!

**Comment by nyannnnnnn** [comment]
Thanks!
