### ISSUE TITLE
Implement in a chat bot

### ISSUE THREAD

**Issue by zhenwei2972** [jerryli27/TwinGAN#27]
Hello! I found the project to be really interesting, do you mind if I implement it in a chat bot to expose it to more people? Not sure if this is the right place to write it

**Comment by jerryli27** [comment]
Hi there! Thanks for your interest in my project! You're more than welcome to migrate/implement this in your chat bot. The license for this project is Apache 2.0.

You may found that the model is not production-ready though. It does not work as well on webcam images and depends largely on the lighting condition. You'll likely need to augment the training data a bit before it is usable.
