### ISSUE TITLE
How many pictures is the training dataset required for the model?

### ISSUE THREAD

**Issue by wyixiang** [jerryli27/TwinGAN#29]
If I want to train a picture translation model myself,  how to set the size of the data set?
I mean, how many pictures from celeba and how many pictures from the anime data set are required to train the model.

**Comment by jerryli27** [comment]
I used 10k+ for anime and around 6k for cats. Numbers may not be exact but on the same order of magnitude.

**Comment by wyixiang** [comment]
Thank you for your quick reply！
