### ISSUE TITLE
How many encoders do you use?

### ISSUE THREAD

**Issue by wyixiang** [jerryli27/TwinGAN#31]
Your paper said that "your TwinGAN architecture uses two encoders, E1 and E2". But in your blog, I saw that "As mentioned in the Facebook paper, letting the human and anime portraits share the same network will help the network realize that......"
So, how many encoders are there in the TwinGAN architecture?

**Comment by jerryli27** [comment]
There are two encoders, one for each domain. They have the same structure and share some weights with each other, namely the conv kernel weights. They do not share the batch normalization parameters (it's similar to AdaIN).

**Comment by wyixiang** [comment]
OK, I get it. Thank you!
