### ISSUE TITLE
About Getchu Dataset

### ISSUE THREAD

**Issue by lionel3** [jerryli27/TwinGAN#8]
Hi, 
I want to convert anime tf-record files to jpg files for Pytorch use.
I noticed that I can only get the one-hot array with the following code:
```
def read_and_decode(filename_queue):
    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)
    features = tf.parse_single_example(
        serialized_example,
        # Defaults are not specified since both keys are required.
        features={
            'image/colorspace': tf.FixedLenFeature([], tf.string),
            'image/channels': tf.FixedLenFeature([], tf.int64),
            'image/format': tf.FixedLenFeature([], tf.string),
            'image/filename': tf.FixedLenFeature([], tf.string),
            'image/encoded': tf.FixedLenFeature([], tf.string),
        })
    image = tf.decode_raw(features['image/encoded'], tf.uint8)
    return image
```
I still need to know the width and height of the array.
Could you please help me with that?

**Comment by jerryli27** [comment]
I'm a bit confused about the "[one-hot](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f)" array part.. Assuming you want to get the image from the tfrecord, you can use the following code:

```
# util_misc.py is provided in the source code.
numpy_image = util_misc.encoded_image_to_numpy(encoded_image['image/encoded'].bytes_list.value[:][0])
```

It should work. If not let me know. Thanks!

**Comment by lionel3** [comment]
It works. Thanks!
I used to use my own code and  can only get arrays like [1, HxWxC], which I call "one-hot" array.
